USE pycon22;

CREATE TABLE `profile` (
    `uid` VARCHAR(32) NOT NULL PRIMARY KEY,
    `name` VARCHAR(128) DEFAULT '',
    `lang` VARCHAR(6),
    `coin` SMALLINT unsigned DEFAULT 0,
	`star` SMALLINT unsigned DEFAULT 0,
    `modified` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
